export type Fuel = "Diesel" | "Benzin" | "Elektro" | "Hybrid";
export type Gearbox = "Automatik" | "Schaltgetriebe";
export type Body = "Limousine" | "Kombi" | "SUV" | "Coupé" | "Cabrio" | "Kompakt" | "Sportwagen";

export interface Vehicle {
  slug: string;
  brand: string;
  model: string;
  variant: string;
  price: number;
  oldPrice?: number;
  year: number;
  firstRegistration: string;
  mileage: number;
  powerKw: number;
  fuel: Fuel;
  gearbox: Gearbox;
  body: Body;
  color: string;
  consumption: string;
  co2: string;
  emissionClass: string;
  images: string[];
  badges: string[];
  featured?: boolean;
  description: string;
  equipment: string[];
  previousOwners: number;
  doors: number;
  seats: number;
}

const img = (n: string) => `/images/${n}.jpg`;

export const vehicles: Vehicle[] = [
  {
    slug: "bmw-740d-xdrive-m-sport",
    brand: "BMW",
    model: "740d xDrive",
    variant: "M Sportpaket · Executive Drive Pro · Bowers & Wilkins",
    price: 74900,
    oldPrice: 78900,
    year: 2022,
    firstRegistration: "03/2022",
    mileage: 38900,
    powerKw: 250,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Limousine",
    color: "Saphirschwarz metallic",
    consumption: "6,4 l/100 km (komb.)",
    co2: "168 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("bmw-7er-front"), img("interior-bmw-m"), img("bmw-front-detail")],
    badges: ["Leasingrückläufer", "Scheckheftgepflegt", "1. Hand"],
    featured: true,
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "Souveräner Auftritt trifft auf modernste Technik: Der 740d xDrive kombiniert den laufruhigen Reihensechszylinder mit Allradantrieb und Luftfederung. Ein Leasingrückläufer aus erster Hand mit lückenloser Historie und vollständigem BMW-Serviceheft.",
    equipment: [
      "M Sportpaket & M Sportbremse",
      "Laserlicht mit BMW Selective Beam",
      "Executive Drive Pro (aktive Wankstabilisierung)",
      "Bowers & Wilkins Diamond Surround Sound",
      "Sitzbelüftung & Massagefunktion vorn",
      "Driving Assistant Professional",
      "Parking Assistant Plus mit Surround View",
      "Head-up Display",
      "Panorama-Glasdach Sky Lounge",
      "Soft-Close-Türen",
    ],
  },
  {
    slug: "bmw-320d-touring-m-sport",
    brand: "BMW",
    model: "320d Touring",
    variant: "M Sport · Live Cockpit Pro · AHK",
    price: 34490,
    year: 2021,
    firstRegistration: "07/2021",
    mileage: 61200,
    powerKw: 140,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Kombi",
    color: "Schwarz metallic",
    consumption: "4,9 l/100 km (komb.)",
    co2: "129 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("bmw-3er-touring"), img("interior-bmw-m"), img("bmw-front-detail")],
    badges: ["Leasingrückläufer", "Scheckheftgepflegt"],
    featured: true,
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Der Alltagsheld mit Sportfaktor: 320d Touring mit M Sportpaket, Anhängerkupplung und dem großen Live Cockpit Professional. Sparsam, geräumig und in gepflegtem Zustand – ideal für Familie und Beruf.",
    equipment: [
      "M Sportpaket, 19\" M Leichtmetallräder",
      "Live Cockpit Professional mit Navigation",
      "Anhängerkupplung elektrisch schwenkbar",
      "LED-Scheinwerfer mit Fernlichtassistent",
      "Sportsitze Leder Vernasca",
      "Rückfahrkamera & Park Distance Control",
      "Sitzheizung vorn, 3-Zonen-Klimaautomatik",
      "Ambientes Licht",
    ],
  },
  {
    slug: "bmw-120i-m-sport",
    brand: "BMW",
    model: "120i",
    variant: "M Sport · LED · Navi · Kamera",
    price: 24980,
    year: 2020,
    firstRegistration: "10/2020",
    mileage: 44800,
    powerKw: 131,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Kompakt",
    color: "Schwarz Saphir metallic",
    consumption: "5,8 l/100 km (komb.)",
    co2: "132 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("bmw-1er-sunset"), img("interior-bmw-m")],
    badges: ["Unfallfrei", "Garantie inklusive"],
    previousOwners: 2,
    doors: 5,
    seats: 5,
    description:
      "Kompakt, agil und hochwertig ausgestattet. Der 120i im M Sport-Design überzeugt mit spritziger Motorisierung, Steptronic-Automatik und moderner Konnektivität.",
    equipment: [
      "M Sportpaket & Sportlenkung",
      "LED-Scheinwerfer",
      "Navigationssystem Live Cockpit Plus",
      "Rückfahrkamera",
      "Apple CarPlay / Android Auto",
      "Sitzheizung vorn",
      "Tempomat mit Bremsfunktion",
    ],
  },
  {
    slug: "mercedes-c-220-d-amg-line",
    brand: "Mercedes-Benz",
    model: "C 220 d",
    variant: "AMG Line · Digital Light · Burmester",
    price: 39900,
    oldPrice: 41900,
    year: 2022,
    firstRegistration: "05/2022",
    mileage: 29500,
    powerKw: 147,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Limousine",
    color: "Polarweiß",
    consumption: "4,8 l/100 km (komb.)",
    co2: "126 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("mercedes-c-klasse"), img("interior-amg"), img("interior-mercedes-wheel")],
    badges: ["Leasingrückläufer", "1. Hand", "Scheckheftgepflegt"],
    featured: true,
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "Die neue C-Klasse in der begehrten AMG Line: Digital Light, das große MBUX-Portrait-Display und Burmester 3D-Sound machen jede Fahrt zum Erlebnis. Ein Fahrzeug aus erster Hand mit vollständiger Mercedes-Historie.",
    equipment: [
      "AMG Line Exterieur & Interieur",
      "DIGITAL LIGHT mit Projektionsfunktion",
      "MBUX Navigation Premium mit Augmented Reality",
      "Burmester 3D-Surround-Soundsystem",
      "Fahrassistenz-Paket Plus",
      "Panorama-Schiebedach",
      "Sitzheizung & Memory-Paket",
      "360°-Kamera, Park-Paket",
      "Keyless-Go, Ambientebeleuchtung 64 Farben",
    ],
  },
  {
    slug: "mercedes-cls-400-d-4matic",
    brand: "Mercedes-Benz",
    model: "CLS 400 d 4MATIC",
    variant: "AMG Line · Distronic · Multibeam LED",
    price: 56800,
    year: 2021,
    firstRegistration: "02/2021",
    mileage: 52300,
    powerKw: 243,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Coupé",
    color: "Diamantweiß bright",
    consumption: "6,1 l/100 km (komb.)",
    co2: "160 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("mercedes-cls"), img("interior-amg"), img("interior-mercedes-wheel")],
    badges: ["Leasingrückläufer", "Scheckheftgepflegt"],
    featured: true,
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "Das viertürige Coupé mit dem 340 PS starken Reihensechszylinder-Diesel und Allradantrieb. Elegante Linie, AMG Line-Ausstattung und Distronic-Abstandsregeltempomat – souverän auf jeder Langstrecke.",
    equipment: [
      "AMG Line, 20\" AMG Leichtmetallräder",
      "MULTIBEAM LED",
      "DISTRONIC Abstandsregeltempomat",
      "Widescreen Cockpit & COMAND Online",
      "Leder Nappa, Sitzklimatisierung",
      "AIR BODY CONTROL Luftfederung",
      "Schiebedach, Standheizung",
      "Burmester Surround-Soundsystem",
    ],
  },
  {
    slug: "mercedes-e-250-cabriolet",
    brand: "Mercedes-Benz",
    model: "E 250 Cabriolet",
    variant: "AMG Sport · Airscarf · Comand",
    price: 32900,
    year: 2019,
    firstRegistration: "06/2019",
    mileage: 68900,
    powerKw: 155,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Cabrio",
    color: "Polarweiß",
    consumption: "6,9 l/100 km (komb.)",
    co2: "158 g/km (komb.)",
    emissionClass: "Euro 6",
    images: [img("mercedes-e-cabrio"), img("mercedes-e-w212"), img("interior-cream")],
    badges: ["Unfallfrei", "Garantie inklusive"],
    previousOwners: 2,
    doors: 2,
    seats: 4,
    description:
      "Offen fahren, ganzjährig genießen: Dank AIRSCARF-Nackenheizung und AIRCAP-Windschott bleibt das E-Klasse Cabriolet auch an kühlen Tagen komfortabel. Gepflegter Zustand mit weißem Leder und AMG Sportpaket.",
    equipment: [
      "AMG Sportpaket",
      "AIRSCARF & AIRCAP",
      "COMAND Online Navigation",
      "Leder weiß, Sitzheizung",
      "LED Intelligent Light System",
      "Rückfahrkamera, Parktronic",
      "Harman Kardon Logic 7",
    ],
  },
  {
    slug: "mercedes-c-300-amg-line",
    brand: "Mercedes-Benz",
    model: "C 300",
    variant: "AMG Line · Night-Paket · Widescreen",
    price: 35900,
    year: 2020,
    firstRegistration: "09/2020",
    mileage: 55100,
    powerKw: 190,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Limousine",
    color: "Polarweiß",
    consumption: "6,6 l/100 km (komb.)",
    co2: "151 g/km (komb.)",
    emissionClass: "Euro 6d-TEMP",
    images: [img("mercedes-c-sunset"), img("interior-amg")],
    badges: ["Scheckheftgepflegt", "Unfallfrei"],
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "258 PS, 9G-TRONIC und das Night-Paket in Hochglanzschwarz: Diese C 300 ist die sportliche Wahl in der Mittelklasse. Aus erster Hand, mit Serviceheft und neuen Bremsen.",
    equipment: [
      "AMG Line & Night-Paket",
      "Widescreen Cockpit",
      "LED High Performance",
      "Rückfahrkamera, Totwinkel-Assistent",
      "Sitzheizung, Klimaautomatik THERMOTRONIC",
      "Keyless-Go, Easy-Pack Heckklappe",
    ],
  },
  {
    slug: "audi-a3-limousine-35-tfsi-s-line",
    brand: "Audi",
    model: "A3 Limousine 35 TFSI",
    variant: "S line · Matrix LED · Virtual Cockpit",
    price: 29900,
    year: 2022,
    firstRegistration: "04/2022",
    mileage: 21400,
    powerKw: 110,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Limousine",
    color: "Daytonagrau perleffekt",
    consumption: "5,5 l/100 km (komb.)",
    co2: "125 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("audi-a3-limousine"), img("audi-a3-rear"), img("audi-s3-road")],
    badges: ["Leasingrückläufer", "1. Hand", "Garantie inklusive"],
    featured: true,
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "Die aktuelle A3 Limousine mit S line-Exterieur, Matrix-LED-Scheinwerfern und Virtual Cockpit plus. Ein junger Leasingrückläufer mit niedriger Laufleistung und Herstellergarantie.",
    equipment: [
      "S line Exterieur & Interieur",
      "Matrix LED-Scheinwerfer",
      "Audi virtual cockpit plus",
      "MMI Navigation plus",
      "Sportsitze, Sitzheizung",
      "Einparkhilfe plus, Rückfahrkamera",
      "Audi pre sense front, Spurhalteassistent",
    ],
  },
  {
    slug: "audi-a4-avant-40-tdi-quattro",
    brand: "Audi",
    model: "A4 Avant 40 TDI quattro",
    variant: "S line · AHK · Panorama · B&O",
    price: 36400,
    year: 2021,
    firstRegistration: "08/2021",
    mileage: 47600,
    powerKw: 150,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Kombi",
    color: "Daytonagrau perleffekt",
    consumption: "5,0 l/100 km (komb.)",
    co2: "131 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("audi-a4-avant"), img("audi-s4-dusk"), img("interior-sport")],
    badges: ["Leasingrückläufer", "Scheckheftgepflegt"],
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Allrad, Anhängerkupplung und Panoramadach: Der A4 Avant 40 TDI quattro ist der perfekte Begleiter für Familie, Urlaub und Alltag. S line-Ausstattung und Bang & Olufsen Sound inklusive.",
    equipment: [
      "S line Exterieur, 19\" Räder",
      "quattro Allradantrieb",
      "Anhängerkupplung schwenkbar",
      "Panorama-Glasdach",
      "Bang & Olufsen 3D Sound",
      "MMI Navigation plus, virtual cockpit",
      "Adaptiver Tempomat, Spurführung",
    ],
  },
  {
    slug: "audi-a7-sportback-50-tdi-quattro",
    brand: "Audi",
    model: "A7 Sportback 50 TDI quattro",
    variant: "S line · HD Matrix · Luftfederung",
    price: 47900,
    year: 2020,
    firstRegistration: "11/2020",
    mileage: 73200,
    powerKw: 210,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "Coupé",
    color: "Florettsilber metallic",
    consumption: "6,0 l/100 km (komb.)",
    co2: "157 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("audi-a7-snow"), img("interior-sport")],
    badges: ["Scheckheftgepflegt", "Unfallfrei"],
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Design-Ikone mit Gran-Turismo-Qualitäten: 286 PS V6-TDI, adaptive Luftfederung und HD Matrix LED. Gepflegt, mit vollständiger Historie und frischem Service.",
    equipment: [
      "S line Sportpaket, 20\" Räder",
      "HD Matrix LED mit Laserlicht",
      "Adaptive air suspension",
      "MMI Navigation plus mit MMI touch response",
      "Leder Valcona, Sitzbelüftung",
      "Bang & Olufsen Premium Sound",
      "Head-up Display, Assistenzpaket Tour",
    ],
  },
  {
    slug: "audi-r8-coupe-v10-performance",
    brand: "Audi",
    model: "R8 Coupé V10 performance",
    variant: "quattro · Keramikbremse · Carbon",
    price: 149900,
    year: 2021,
    firstRegistration: "03/2021",
    mileage: 12900,
    powerKw: 456,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Sportwagen",
    color: "Suzukagrau metallic",
    consumption: "13,1 l/100 km (komb.)",
    co2: "297 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("audi-r8"), img("interior-sport")],
    badges: ["1. Hand", "Sammlerzustand"],
    featured: true,
    previousOwners: 1,
    doors: 2,
    seats: 2,
    description:
      "620 PS Saugmotor, Mittelmotor-Layout und quattro: Der R8 V10 performance ist ein Supersportler zum täglichen Fahren. Aus erster Hand, garagengepflegt, mit Carbon-Paket und Keramikbremsanlage.",
    equipment: [
      "V10 5.2 FSI performance, 620 PS",
      "Keramikbremsanlage",
      "Carbon-Exterieurpaket & Carbon-Seitenblades",
      "Laserlicht",
      "Bang & Olufsen Sound",
      "Schalensitze Leder Feinnappa",
      "Sportabgasanlage",
    ],
  },
  {
    slug: "porsche-911-carrera-s-992",
    brand: "Porsche",
    model: "911 Carrera S (992)",
    variant: "PDK · Sport Chrono · PASM · BOSE",
    price: 129900,
    year: 2021,
    firstRegistration: "05/2021",
    mileage: 18700,
    powerKw: 331,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Sportwagen",
    color: "Tiefschwarz metallic",
    consumption: "10,1 l/100 km (komb.)",
    co2: "229 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("porsche-911-black"), img("porsche-garage"), img("interior-luxury-portrait")],
    badges: ["Porsche Approved", "1. Hand", "Scheckheftgepflegt"],
    featured: true,
    previousOwners: 1,
    doors: 2,
    seats: 4,
    description:
      "Die Ikone in ihrer aktuellen Generation: 450 PS, 8-Gang-PDK, Sport Chrono Paket und PASM Sportfahrwerk. Ein Fahrzeug aus erster Hand mit Porsche Approved Garantie.",
    equipment: [
      "Sport Chrono Paket",
      "PASM Sportfahrwerk (-10 mm)",
      "Sportabgasanlage",
      "LED-Matrix Hauptscheinwerfer inkl. PDLS Plus",
      "BOSE Surround Sound System",
      "18-Wege Sportsitze Plus",
      "Porsche Communication Management",
      "Lift-System Vorderachse",
    ],
  },
  {
    slug: "porsche-911-carrera-4-gts",
    brand: "Porsche",
    model: "911 Carrera 4 GTS",
    variant: "PDK · Sport-Design · Lift · Carbon",
    price: 154900,
    year: 2022,
    firstRegistration: "06/2022",
    mileage: 9800,
    powerKw: 353,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Sportwagen",
    color: "Pythongrün",
    consumption: "10,4 l/100 km (komb.)",
    co2: "236 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("porsche-911-green"), img("interior-luxury-portrait"), img("porsche-garage")],
    badges: ["Porsche Approved", "1. Hand", "Sonderfarbe"],
    previousOwners: 1,
    doors: 2,
    seats: 4,
    description:
      "480 PS, Allradantrieb und die seltene Sonderfarbe Pythongrün: Dieser Carrera 4 GTS ist ein echter Hingucker mit Sammlerpotenzial. Erstbesitz, nahezu neuwertig.",
    equipment: [
      "GTS Interieur-Paket Carbon",
      "Sport Chrono Paket",
      "Lift-System Vorderachse",
      "Sportabgasanlage GTS",
      "Matrix LED, PDLS Plus",
      "BOSE Surround Sound",
      "Rückfahrkamera, Surround View",
    ],
  },
  {
    slug: "vw-golf-gti-viii",
    brand: "Volkswagen",
    model: "Golf GTI",
    variant: "DSG · IQ.Light · Harman Kardon · Pano",
    price: 33900,
    year: 2022,
    firstRegistration: "02/2022",
    mileage: 24300,
    powerKw: 180,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Kompakt",
    color: "Kings Red metallic",
    consumption: "7,0 l/100 km (komb.)",
    co2: "160 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("vw-golf-gti-red"), img("vw-golf-gti-white"), img("interior-sport")],
    badges: ["Leasingrückläufer", "1. Hand", "Garantie inklusive"],
    featured: true,
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Der Klassiker unter den Hot Hatches: 245 PS, DSG, IQ.Light Matrix-LED und das Harman Kardon Soundsystem. Ein Leasingrückläufer aus erster Hand mit Herstellergarantie.",
    equipment: [
      "IQ.Light LED-Matrix-Scheinwerfer",
      "Harman Kardon Soundsystem",
      "Panorama-Schiebedach",
      "Discover Pro Navigation",
      "Travel Assist, Area View",
      "Sportsitze Top-Sport",
      "19\" Estoril Leichtmetallräder",
    ],
  },
  {
    slug: "vw-golf-8-style-1-5-etsi",
    brand: "Volkswagen",
    model: "Golf 8 Style 1.5 eTSI",
    variant: "DSG · LED Plus · Navi · ACC",
    price: 24490,
    year: 2021,
    firstRegistration: "09/2021",
    mileage: 39800,
    powerKw: 110,
    fuel: "Hybrid",
    gearbox: "Automatik",
    body: "Kompakt",
    color: "Atlantic Blue metallic",
    consumption: "5,2 l/100 km (komb.)",
    co2: "118 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("vw-golf-blue"), img("vw-golf-7-black")],
    badges: ["Unfallfrei", "Garantie inklusive"],
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Effizienter Mild-Hybrid mit 150 PS und 7-Gang-DSG. Die Style-Ausstattung bringt LED Plus, Navigation und ACC – ein moderner Golf zum fairen Preis.",
    equipment: [
      "LED Plus Scheinwerfer",
      "Discover Media Navigation",
      "ACC Abstandsregeltempomat",
      "Digital Cockpit Pro",
      "Klimaautomatik Air Care",
      "Sitzheizung vorn, Lenkradheizung",
      "App-Connect wireless",
    ],
  },
  {
    slug: "vw-golf-r-performance",
    brand: "Volkswagen",
    model: "Golf R 2.0 TSI 4MOTION",
    variant: "Performance-Paket · Akrapovič · DCC",
    price: 42900,
    year: 2022,
    firstRegistration: "08/2022",
    mileage: 27500,
    powerKw: 235,
    fuel: "Benzin",
    gearbox: "Automatik",
    body: "Kompakt",
    color: "Pure White",
    consumption: "7,8 l/100 km (komb.)",
    co2: "177 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("vw-golf-r-white"), img("vw-golf-gti-white"), img("interior-sport")],
    badges: ["1. Hand", "Scheckheftgepflegt"],
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "320 PS, Allrad mit R-Performance Torque Vectoring und Akrapovič-Titanabgasanlage: Der Golf R mit Performance-Paket ist ein Kompaktsportler ohne Kompromisse.",
    equipment: [
      "R-Performance-Paket inkl. Drift-Modus",
      "Akrapovič Titan-Abgasanlage",
      "DCC adaptive Fahrwerksregelung",
      "IQ.Light, Head-up Display",
      "Harman Kardon Soundsystem",
      "19\" Estoril, Sportsitze Nappa",
    ],
  },
  {
    slug: "tesla-model-3-long-range",
    brand: "Tesla",
    model: "Model 3 Long Range AWD",
    variant: "Dual Motor · Autopilot · Premium Interieur",
    price: 36900,
    oldPrice: 38900,
    year: 2022,
    firstRegistration: "01/2022",
    mileage: 31200,
    powerKw: 366,
    fuel: "Elektro",
    gearbox: "Automatik",
    body: "Limousine",
    color: "Deep Blue metallic",
    consumption: "16,0 kWh/100 km (komb.)",
    co2: "0 g/km (komb.)",
    emissionClass: "Elektro",
    images: [img("tesla-model-3-blue"), img("tesla-model-3-white"), img("tesla-road"), img("tesla-model-3-red")],
    badges: ["Leasingrückläufer", "Batteriegarantie bis 2030"],
    featured: true,
    previousOwners: 1,
    doors: 4,
    seats: 5,
    description:
      "Bis zu 602 km Reichweite (WLTP), Allradantrieb und Autopilot: Das Model 3 Long Range ist der ideale Einstieg in die Elektromobilität – mit Premium-Interieur und Wärmepumpe.",
    equipment: [
      "Dual Motor Allradantrieb",
      "Autopilot inkl. Navigate on Autopilot",
      "Premium Interieur mit Glasdach",
      "Premium-Audio 14 Lautsprecher",
      "Wärmepumpe",
      "Sitzheizung vorn & hinten",
      "19\" Sport-Felgen",
    ],
  },
  {
    slug: "range-rover-evoque-d200-r-dynamic",
    brand: "Land Rover",
    model: "Range Rover Evoque D200",
    variant: "R-Dynamic SE · Pano · Meridian",
    price: 41900,
    year: 2021,
    firstRegistration: "04/2021",
    mileage: 41700,
    powerKw: 150,
    fuel: "Diesel",
    gearbox: "Automatik",
    body: "SUV",
    color: "Fuji White",
    consumption: "5,9 l/100 km (komb.)",
    co2: "155 g/km (komb.)",
    emissionClass: "Euro 6d",
    images: [img("range-rover-evoque-white"), img("interior-range-rover"), img("range-rover-evoque-red")],
    badges: ["Scheckheftgepflegt", "Garantie inklusive"],
    previousOwners: 1,
    doors: 5,
    seats: 5,
    description:
      "Kompaktes Luxus-SUV mit Mild-Hybrid-Diesel, Allradantrieb und dem Panorama-Glasdach. R-Dynamic-Optik, Meridian-Sound und Pivi Pro Navigation.",
    equipment: [
      "R-Dynamic SE Exterieur",
      "Panorama-Glasdach",
      "Meridian Soundsystem",
      "Pivi Pro Navigation, ClearSight Innenspiegel",
      "Matrix LED, 360°-Kamera",
      "Leder, Sitzheizung, Lenkradheizung",
    ],
  }
];

export const brands = Array.from(new Set(vehicles.map((v) => v.brand))).sort();
export const getVehicle = (slug: string) => vehicles.find((v) => v.slug === slug);
export const featuredVehicles = vehicles.filter((v) => v.featured);
export const ps = (kw: number) => Math.round(kw * 1.35962);
